config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :courses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "welcomes#index"
  resources :students

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :student
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
  validates_presence_of :name, :description
end

app/models/demo.rb
class Demo < ApplicationRecord
  has_one :sub_demo
end

app/models/department.rb
class Department < ApplicationRecord
  has_one :manager
  has_one :manager_history, through: :manager
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :department
  has_one :manager_history
end

app/models/manager_history.rb
class ManagerHistory < ApplicationRecord
  belongs_to :manager
end

app/models/news.rb
class News < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :student_projects
  has_many :students, through: :student_projects
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :blogs
  has_and_belongs_to_many :courses
  has_many :student_projects
  has_many :projects, through: :student_projects
  validates_presence_of :first_name, :lastname,
                        :email, :phonenumber, :dob, 
                        :permanent_contact_number, 
                        :local_address, 
                        :permanent_address, 
                        :alternate_contact_number 
  before_create :display_message

  def display_message
    p 'hello, this is a message before create action'
  end

  def full_name
    "#{first_name}#{lastname}"
  end

  def student_with_email
    "#{full_name} / #{email}"
  end
end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/models/sub_demo.rb
class SubDemo < ApplicationRecord
  belongs_to :demo
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController

    # TODO - Implement CRUD Operations Later 

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout 'admin'
  before_action :set_student, only: %i[show edit update destroy]
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: 'Student has been created successfully'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to student_path, notice: 'Student has been updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:first_name, 
                                    :lastname,
                                    :email,
                                    :phonenumber, 
                                    :dob, 
                                    "permanent_contact_number", 
                                    "local_address",
                                    "permanent_address",
                                    "alternate_contact_number" )
  end

  def set_student
    @student = Student.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>
  <% if @student.errors.any? %>
    <% @student.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :phonenumber %>
    <%= form.text_field :phonenumber, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :date_of_birth %>
    <%= form.date_field :dob, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :permanent_contact_number %>
    <%= form.text_field :permanent_contact_number, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :alternate_contact_number %>
    <%= form.text_field :alternate_contact_number, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :local_address %>
    <%= form.text_field :local_address, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <%= form.label :permanent_address %>
    <%= form.text_field :permanent_address, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
  <%= form.submit class: "btn btn-primary" %> <%= link_to "Back", students_path, class: "btn btn-secondary" %>
  </div>
  
<% end %>

app/views/students/edit.html.erb
<div class="col-lg-8">
  <h1>Edit Student Details </h1>
  <%= render "form" , student: @student %>
</div>

app/views/students/index.html.erb
<div class="col-lg-10">
  <p> <%= notice %> </p>
  <h1>List of all students</h1>
  <%= link_to 'New Student', new_student_path, class: "btn btn-primary" %><br>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan='3'>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td><%= student.student_with_email %></td>
        <td><%= link_to 'Show', student_path(student) %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<div class="col-lg-8">
<h1> New Student </h1>

<%= render "form", student: @student %>
</div>

app/views/students/show.html.erb
<div class="col-lg-10">
  <div class="card rounded-0 shadow mt-5 md-5">
    <div class="card-body">
      <p> <%= notice %> </p>
      <h1>Student Information</h1>
      <p>
        <strong>First Name: </strong><%= @student.first_name %>
      </p>
      <p>
        <strong>Last Name: </strong><%= @student.lastname %>
      </p>
      <p>
        <strong>Email: </strong><%= @student.email %>
      </p>
      <p>
        <strong>Phonenumber: </strong><%= @student.phonenumber %>
      </p>
      <p>
        <strong>Date of birth: </strong><%= @student.dob %>
      </p>
      <p>
        <strong>Permanent contact number: </strong><%= @student.permanent_contact_number %>
      </p>
      <p>
        <strong>Alternate contact number: </strong><%= @student.alternate_contact_number %>
      </p>
      <p>
        <strong>Local address: </strong><%= @student.local_address %>
      </p>
      <p>
        <strong>Permanent address: </strong><%= @student.permanent_address %>
      </p>
      <div>
        <%= link_to "Back", students_path, class: "btn btn-primary" %> 
        <%= link_to "Edit", edit_student_path(@student), class: "btn btn-secondary" %>
      </div>  
    </div>
  </div>
</div>